# Generated by Django 5.1.3 on 2024-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snils', models.TextField(verbose_name='СНИЛС')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('name', models.TextField(verbose_name='Имя')),
                ('middle_name', models.TextField(verbose_name='Отчество')),
                ('date_of_birth', models.TextField(verbose_name='Дата рождения')),
                ('place_of_birth', models.TextField(verbose_name='Место рождения')),
                ('gender', models.TextField(verbose_name='Пол')),
                ('passport_place', models.TextField(verbose_name='Место выдачи паспорта')),
                ('passport_date', models.TextField(verbose_name='Дата выдачи паспорта')),
                ('departament_code', models.TextField(verbose_name='Код подразделения')),
                ('place_of_residence', models.TextField(verbose_name='Место жительства')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиника',
                'db_table': 'clinic',
            },
        ),
    ]
