# Generated by Django 5.1.3 on 2024-12-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upldfile/')),
            ],
        ),
    ]
