# Generated by Django 5.1.3 on 2025-01-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0003_clinic_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesave',
            name='file',
        ),
        migrations.AddField(
            model_name='filesave',
            name='file_lvplc',
            field=models.FileField(default=0, upload_to='upldfile/live_place/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesave',
            name='file_passport',
            field=models.FileField(default=0, upload_to='upldfile/passport/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesave',
            name='file_snils',
            field=models.FileField(default=0, upload_to='upldfile/snils/'),
            preserve_default=False,
        ),
    ]
