# Generated by Django 5.1.4 on 2025-01-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0004_remove_filesave_file_filesave_file_lvplc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesave',
            name='file_lvplc',
            field=models.FileField(blank=True, null=True, upload_to='upldfile/live_place/'),
        ),
        migrations.AlterField(
            model_name='filesave',
            name='file_passport',
            field=models.FileField(blank=True, null=True, upload_to='upldfile/passport/'),
        ),
        migrations.AlterField(
            model_name='filesave',
            name='file_snils',
            field=models.FileField(blank=True, null=True, upload_to='upldfile/snils/'),
        ),
    ]
