# Generated by Django 5.1.4 on 2025-01-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0005_alter_filesave_file_lvplc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesave',
            name='file_lvplc',
            field=models.FileField(default=0, upload_to='upldfile/live_place/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filesave',
            name='file_passport',
            field=models.FileField(default=0, upload_to='upldfile/passport/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filesave',
            name='file_snils',
            field=models.FileField(default=0, upload_to='upldfile/snils/'),
            preserve_default=False,
        ),
    ]
